name: Play a Game on Profile

on:
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day
  workflow_dispatch:

jobs:
  update-game:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Play a Game
        uses: DenverCoder1/play-a-game-on-github-profile@v1 # Gunakan '@v1'
        with:
          game: pacman # Anda bisa ganti dengan snake, tetris, dll.
